---
id: Prefs
name: Prefs
full: User preferences library
description: >-
  A library that provides a common abstracted interface into  various
  preferences storage mediums. It also includes all of the functions for
  retrieving, storing, and checking preference values.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Prefs
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha3
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
    composer:
      horde/exception: ^3
      horde/mail: ^3
      horde/mime: ^3
      horde/translation: ^3
      horde/util: ^3
    ext:
      json: '*'
  optional:
    composer:
      horde/autoloader: ^3
      horde/cache: ^3
      horde/db: ^3
      horde/image: ^3
      horde/imsp: ^3
      horde/kolab_storage: ^3
      horde/ldap: ^3
      horde/mongo: ^2
      horde/test: ^3
